[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    ". /app/.venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /app/.venv/bin/activate && python manage.py collectstatic --no-input",
    ". /app/.venv/bin/activate && python manage.py migrate"
]

[start]
cmd = "/app/.venv/bin/gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT"
